### ISSUE TITLE
Runner deploy unwanted files in the workspace directory

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/distribution#22]
**Description:**
My `<SIDDHI-RUNNER-HOME>/wso2/worker/deployment/siddhi-files/` directory contains some of the system link sub-directories and files such as 

`drwxr-xr-x 2 root root 4096 Mar 18 10:06 ..2019_03_18_10_06_42.481700548`
`lrwxrwxrwx 1 root root   31 Mar 18 10:06 ..data -> ..2019_03_18_10_06_42.481700548` 

apart from my `*.siddhi` files. When I tried to deploy siddhi files in the `<SIDDHI-RUNNER-HOME>/wso2/worker/deployment/siddhi-files` directory, it tries to deploy that system link sub-directories and files, then gives an error as,

`[2019-03-18 10:06:50,993] ERROR {io.siddhi.distribution.core.core.internal.StreamProcessorDeployer} - /home/siddhi-runner-1.0.0-SNAPSHOT/wso2/worker/deployment/siddhi-files/..data (Is a directory) java.io.FileNotFoundException: /home/siddhi-runner-1.0.0-SNAPSHOT/wso2/worker/deployment/siddhi-files/..data (Is a directory)`

So, it's better to have the capability to filter only the siddhi files from `<SIDDHI-RUNNER-HOME>/wso2/worker/deployment/siddhi-files` directory and deploy, instead of deploying all the files in that directory.

**Comment by BuddhiWathsala** [comment]
Here I attached the stack-trace 
```
[2019-05-21 14:53:12,960] ERROR {io.siddhi.distribution.core.internal.StreamProcessorDeployer} - /home/siddhi_user/siddhi-runner-0.1.0/wso2/runner/deployment/siddhi-files/..data (Is a directory) java.io.FileNotFoundException: /home/siddhi_user/siddhi-runner-0.1.0/wso2/runner/deployment/siddhi-files/..data (Is a directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:79)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:292)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.start(DeploymentEngine.java:121)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngineListenerComponent.onAllRequiredCapabilitiesAvailable(DeploymentEngineListenerComponent.java:216)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.lambda$notifySatisfiableComponents$7(StartupComponentManager.java:266)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupComponentManager.notifySatisfiableComponents(StartupComponentManager.java:252)
	at org.wso2.carbon.kernel.internal.startupresolver.StartupOrderResolver$1.run(StartupOrderResolver.java:204)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
