### ISSUE TITLE
Startup error for Siddhi tooling distribution

### ISSUE THREAD

**Issue by mohanvive** [siddhi-io/distribution#224]
**Description:**
Gives below error when starting the siddhi tooling distribution in mac..

```
Mohanadarshans-MacBook-Pro:bin mohan$ ./tooling.sh 
JAVA_HOME environment variable is set to /Library/Java/JavaVirtualMachines/jdk1.8.0_212.jdk/Contents/Home
CARBON_HOME environment variable is set to /Users/mohan/source-code/mohan/distribution/tooling/target/siddhi-tooling-5.1.0-SNAPSHOT
RUNTIME_HOME environment variable is set to /Users/mohan/source-code/mohan/distribution/tooling/target/siddhi-tooling-5.1.0-SNAPSHOT/wso2/tooling
[2019-07-09 18:14:23,422]  INFO {org.wso2.carbon.launcher.extensions.OSGiLibBundleDeployerUtils updateOSGiLib} - Successfully updated the OSGi bundle information of Carbon Runtime: tooling  
osgi> org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; osgi.identity="org.ops4j.pax.logging.pax-logging-log4j2"; type="osgi.bundle"; version:Version="1.10.0" [id=5] STARTED [STARTED]
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337)
	at org.eclipse.osgi.container.Module.start(Module.java:401)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.startBundles(ConfigApplier.java:453)
	at org.eclipse.equinox.internal.simpleconfigurator.ConfigApplier.install(ConfigApplier.java:111)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:191)
	at org.eclipse.equinox.internal.simpleconfigurator.SimpleConfiguratorImpl.applyConfiguration(SimpleConfiguratorImpl.java:205)
	at org.eclipse.equinox.internal.simpleconfigurator.Activator.start(Activator.java:60)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:774)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:767)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:724)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:932)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309)
	at org.eclipse.osgi.container.Module.doStart(Module.java:581)
	at org.eclipse.osgi.container.Module.start(Module.java:449)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.wso2.carbon.launcher.CarbonServer.loadInitialBundles(CarbonServer.java:242)
	at org.wso2.carbon.launcher.CarbonServer.start(CarbonServer.java:83)
	at org.wso2.carbon.launcher.Main.main(Main.java:84)
Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
	at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334)
	... 22 more
[2019-07-09 18:14:49,939]  INFO {org.wso2.msf4j.internal.websocket.WebSocketServerSC} - All required capabilities are available of WebSocket service component is available.
[2019-07-09 18:14:49,961]  INFO {org.wso2.carbon.metrics.core.config.model.JmxReporterConfig} - Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
[2019-07-09 18:14:49,980]  INFO {org.wso2.msf4j.analytics.metrics.MetricsComponent} - Metrics Component is activated
[2019-07-09 18:14:49,982]  INFO {org.wso2.carbon.databridge.agent.internal.DataAgentDS} - Successfully deployed Agent Server 
[2019-07-09 18:14:50,089]  INFO {io.siddhi.distribution.editor.core.internal.WorkspaceDeployer} - Workspace artifact deployer initiated.
[2019-07-09 18:14:50,093]  INFO {io.siddhi.distribution.event.simulator.core.service.CSVFileDeployer} - CSV file deployer initiated.
[2019-07-09 18:14:50,095]  INFO {io.siddhi.distribution.event.simulator.core.service.SimulationConfigDeployer} - Simulation config deployer initiated.

osgi> 
osgi> [2019-07-09 18:15:09,647]  INFO {io.siddhi.distribution.editor.core.internal.StartupComponent} - Editor Started on : http://10.100.0.99:9390/editor
[2019-07-09 18:15:09,647]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available

osgi> 
osgi> [2019-07-09 18:15:14,710]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9390
[2019-07-09 18:15:14,710]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9743
[2019-07-09 18:15:14,739]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiverServiceComponent} - org.wso2.carbon.databridge.receiver.binary.internal.Service Component is activated
[2019-07-09 18:15:14,742]  INFO {org.wso2.carbon.databridge.receiver.thrift.internal.ThriftDataReceiverDS} - Service Component is activated
[2019-07-09 18:15:14,745]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - Siddhi Tooling Distribution started in 56.678 sec

```

**Comment by mohanvive** [comment]
This is due to Slow JVM in Mac OS - High Sierra
configure /etc/hosts localhost's with what you get when you type "hostname" in terminal

Reference - https://github.com/wso2/product-sp/issues/198
