### ISSUE TITLE
Siddhi App fails to deploy due to extensions not loading with -Dapps argument

### ISSUE THREAD

**Issue by dasuni-30** [siddhi-io/distribution#368]
When deploying the Siddhi app in docker using the -Dapps argument, an exception is thrown because extensions necessary for deployment did not load prior to the deployment.
![Screenshot from 2019-09-05 17-09-53](https://user-images.githubusercontent.com/27746285/64338787-350afa00-d000-11e9-99d4-a939c066f60a.png)

**Comment by dasuni-30** [comment]
Still facing the issue even after retrying in 5.1.0-beta docker image.
Below is the stacktrace.
```
[2019-09-18 06:23:26,123]  WARN {io.siddhi.distribution.core.internal.StreamProcessorDeployer} - Siddhi App HelloWorldApp.siddhi deployment held back due to Error on 'HelloWorldApp' @ Line: 4. Position: 85, near '@source(type = 'http', receiver.url = "http://0.0.0.0:8006/cargo", @map(type='json'))'. No extension exist for sourceMapper:json. Retry deployment will activate soon
[2019-09-18 06:23:26,713]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
[2019-09-18 06:23:26,811]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9090
[2019-09-18 06:23:26,811]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9443
[2019-09-18 06:23:26,817]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - Siddhi Runner Distribution started in 9.132 sec

osgi> 
osgi> [2019-09-18 06:23:56,582] ERROR {io.siddhi.distribution.core.internal.ServiceComponent} - Error occurred in the retry app deployment task for Siddhi App HelloWorldApp.siddhi io.siddhi.core.exception.SiddhiAppCreationException: Error on 'HelloWorldApp' @ Line: 4. Position: 85, near '@source(type = 'http', receiver.url = "http://0.0.0.0:8006/cargo", @map(type='json'))'. No extension exist for sourceMapper:json
	at io.siddhi.core.util.SiddhiClassLoader.loadExtensionImplementation(SiddhiClassLoader.java:45)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSource(DefinitionParserHelper.java:354)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:117)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:374)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:230)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:85)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:95)
	at io.siddhi.distribution.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:69)
	at io.siddhi.distribution.core.internal.ServiceComponent$RetrySiddhiAppDeployment.run(ServiceComponent.java:374)
```

**Comment by mohanvive** [comment]
Fixed with below PRs.
- https://github.com/siddhi-io/siddhi/pull/1507
- https://github.com/siddhi-io/distribution/pull/376
