### ISSUE TITLE
Null pointer exception when providng incorrect database name in rdbms:query

### ISSUE THREAD

**Issue by PrabodDunuwila** [siddhi-io/distribution#428]
**Description:**

When providing incorrect database name this exception occurs in rdbms:query.
(rdbms:cud also has this issue)

eg : When you don't have a database named Customers and you write the query as,
### 
from ### DataStream#rdbms:query('**Customers**', 'select name,amount from CustomerTable  where name=?', name, 'selectName string,amount int')
select selectName,amount
insert into RecordStream;

ERROR {io.siddhi.core.SiddhiAppRuntimeImpl} - Error starting Siddhi App 'Query-rdbms', triggering shutdown process. Datasource 'Customer' cannot be connected.
ERROR {io.siddhi.core.stream.StreamJunction} - Error in 'Query-rdbms' after consuming events from Stream 'DataStream', null. Hence, dropping event 'Event{timestamp=1568885284452, data=[prabod], isExpired=false}' java.lang.NullPointerException
	at io.siddhi.extension.execution.rdbms.QueryStreamProcessor.getConnection(QueryStreamProcessor.java:291)
	at io.siddhi.extension.execution.rdbms.QueryStreamProcessor.process(QueryStreamProcessor.java:248)
	at io.siddhi.core.query.processor.stream.StreamProcessor.processEventChunk(StreamProcessor.java:41)
	at io.siddhi.core.query.processor.stream.AbstractStreamProcessor.process(AbstractStreamProcessor.java:132)
	at io.siddhi.core.query.input.ProcessStreamReceiver.processAndClear(ProcessStreamReceiver.java:183)
	at io.siddhi.core.query.input.ProcessStreamReceiver.process(ProcessStreamReceiver.java:90)
	at io.siddhi.core.query.input.ProcessStreamReceiver.receive(ProcessStreamReceiver.java:128)
	at io.siddhi.core.stream.StreamJunction.sendEvent(StreamJunction.java:199)
	at io.siddhi.core.stream.StreamJunction$Publisher.send(StreamJunction.java:474)
	at io.siddhi.core.stream.input.InputDistributor.send(InputDistributor.java:34)
	at io.siddhi.core.stream.input.InputEntryValve.send(InputEntryValve.java:45)
	at io.siddhi.core.stream.input.InputHandler.send(InputHandler.java:73)
	at io.siddhi.distribution.editor.core.internal.DebuggerEventStreamService.pushEvent(DebuggerEventStreamService.java:74)
	at io.siddhi.distribution.event.simulator.core.internal.generator.SingleEventGenerator.sendEvent(SingleEventGenerator.java:85)
	at io.siddhi.distribution.event.simulator.core.impl.SingleApiServiceImpl.runSingleSimulation(SingleApiServiceImpl.java:20)
	at io.siddhi.distribution.event.simulator.core.api.SingleApi.runSingleSimulation(SingleApi.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by niveathika** [comment]
This is due to sending simulation events, even if the siddhi app is not running. Should be fixed in the UI

**Comment by niveathika** [comment]
Due to the issue, https://github.com/siddhi-io/distribution/issues/461.

Closing this as it is tracked in https://github.com/siddhi-io/distribution/issues/461
