### ISSUE TITLE
[Editor] too many open files 

### ISSUE THREAD

**Issue by suhothayan** [siddhi-io/distribution#540]
**Description:**
```
java    12176 suho 8919r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8920r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8921r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8922r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8923r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8924r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8925r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8926r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8927r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8928r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8930r     DIR                1,4       288 38482690 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/wso2/tooling/deployment/workspace
java    12176 suho 8931w     REG                1,4     13112 38521881 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/20778237977696450020856309880.tmp
java    12176 suho 8932w     REG                1,4       529 38521882 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/856347398623460618726081245.tmp
java    12176 suho 8933w     REG                1,4      2730 38521885 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/515680031763838873175247277.tmp
java    12176 suho 8934w     REG                1,4      1120 38521887 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/1828358727628521912163644120.tmp
java    12176 suho 8935w     REG                1,4      1159 38521888 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/20341754952023740080101912905.tmp
java    12176 suho 8936w     REG                1,4      1189 38521891 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/3441924674474703601499016785.tmp
java    12176 suho 8937w     REG                1,4      1787 38521893 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/7540910892521549300855930778.tmp
java    12176 suho 8938w     REG                1,4      1283 38521895 /Users/suho/wso2/src/suhothayan/distribution/tooling/target/siddhi-tooling-5.1.1-SNAPSHOT/tmp/3315325326157272323813600196.tmp
```

**Comment by niveathika** [comment]
Couldn't reproduce this. Opened around 30 tabs and tried updating them.

**Comment by BuddhiWathsala** [comment]
Getting the same kind of issue. Find the error log below.

```sh
[2020-01-09 12:57:50,076] ERROR {io.siddhi.distribution.editor.core.internal.DebugRuntime} - Siddhi App 'BusDelayAnalysis' is in faulty state. io.siddhi.core.exception.SiddhiAppCreationException: Error on 'BusDelayAnalysis' @ Line: 16. Position: 26, near '@sink(type='http-call', publisher.url='https://api.tfl.gov.uk/line/{{routeNo}}/timetable/{{stopId}}', method='GET', sink.id='timetable',
        @map(type='json'))'. failed to create a child event loop
	at io.siddhi.core.util.ExceptionUtil.populateQueryContext(ExceptionUtil.java:43)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSink(DefinitionParserHelper.java:588)
	at io.siddhi.core.util.SiddhiAppRuntimeBuilder.defineStream(SiddhiAppRuntimeBuilder.java:119)
	at io.siddhi.core.util.parser.SiddhiAppParser.defineStreamDefinitions(SiddhiAppParser.java:374)
	at io.siddhi.core.util.parser.SiddhiAppParser.parse(SiddhiAppParser.java:230)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:85)
	at io.siddhi.core.SiddhiManager.createSiddhiAppRuntime(SiddhiManager.java:95)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.createRuntime(DebugRuntime.java:201)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.<init>(DebugRuntime.java:56)
	at io.siddhi.distribution.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:38)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.start(EditorMicroservice.java:761)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.startWithVariables(EditorMicroservice.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:52)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:87)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:82)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:63)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:51)
	at org.wso2.transport.http.netty.contractimpl.DefaultHttpWsConnectorFactory.<init>(DefaultHttpWsConnectorFactory.java:65)
	at io.siddhi.extension.io.http.sink.util.HttpSinkUtil.createConnectorFactory(HttpSinkUtil.java:343)
	at io.siddhi.extension.io.http.sink.HttpSink.init(HttpSink.java:565)
	at io.siddhi.extension.io.http.sink.HttpCallSink.init(HttpCallSink.java:448)
	at io.siddhi.core.stream.output.sink.Sink.init(Sink.java:102)
	at io.siddhi.core.util.parser.helper.DefinitionParserHelper.addEventSink(DefinitionParserHelper.java:549)
	... 21 more
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:149)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 33 more
Caused by: java.io.IOException: Too many open files
	at sun.nio.ch.KQueueArrayWrapper.init(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.<init>(KQueueArrayWrapper.java:98)
	at sun.nio.ch.KQueueSelectorImpl.<init>(KQueueSelectorImpl.java:88)
	at sun.nio.ch.KQueueSelectorProvider.openSelector(KQueueSelectorProvider.java:42)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:173)
	... 37 more
```

#### Steps to reproduce
1. Deploy the following Siddhi app in Siddhi tooling 5.1.2.

    ```sql
    @App:name("BusDelayAnalysis")
    @App:description("Bus Delay Analysis based on TFL data.")

    @sink(type='http-call', publisher.url='https://api.tfl.gov.uk/line/{{routeNo}}/stoppoints', method='GET', sink.id='stops',
            @map(type='json'))
    define stream RouteStream(routeNo string);

    --@sink(type='log')
    @source(type='http-call-response', sink.id='stops',
            @map(type='json', @attributes('trp:routeNo', 'id', 'commonName')))
    define stream BusStopsStream(routeNo string, stopId string, stopName string);

    @sink(type='http-call', publisher.url='https://api.tfl.gov.uk/line/{{routeNo}}/timetable/{{stopId}}', method='GET', sink.id='timetable',
            @map(type='json'))
    define stream TimeTableRequestStream(routeNo string, stopId string);

    @source(type='http-call-response', sink.id='timetable',
            @map(type='json', enclosing.element='$.timetable.routes[0].schedules',
                @attributes('trp:routeNo', 'trp:stopId', 'name', 'knownJourneys')))
    define stream TimeTableResponseStream(routeNo string, stopId string, dayRange string, knownJourneys string);

    define table BusTimeTable(routeNo string, stopId string, dayRange string, hour int, minute int);

    -- @sink(type='log')
    -- define stream TimeTable(routeNo string, stopId string, dayRange string, hour int, minute int);
    -- define stream TimeTable(routeNo string, stopId string, dayRange string, jsonElement string);

    @sink(type='http-call', publisher.url='https://api.tfl.gov.uk/line/{{routeNo}}/arrivals', method='GET', sink.id='arrivals',
            @map(type='json'))
    define stream ArrivalRouteStream(routeNo string);


    @source(type='http-call-response', sink.id='arrivals',
            @map(type='json', @attributes('trp:routeNo', 'naptanId', 'stationName', 'expectedArrival', 'timeToLive', 'timeToStation')))
    define stream ArrivalsResponseStream(routeNo string, stopId string, stopName string, expectedArrival string, timeToLive string,
                                    timeToStation int);

    @sink(type='log')
    define stream ArrivalAnalysisStream(routeNo string, stopId string, stopName string, hour int, minute int, arrivalHour int, arrivalMin int, timeDiff double, status string);

    from BusStopsStream
    select routeNo, stopId
    insert into TimeTableRequestStream;

    from TimeTableResponseStream[not (knownJourneys is null)]#json:tokenize(knownJourneys, '$')
    select routeNo, stopId, dayRange, json:getInt(jsonElement, 'hour') as hour,  json:getInt(jsonElement, 'minute') as minute
    insert into BusTimeTable;

    from ArrivalsResponseStream
    select routeNo, stopId, stopName,
            time:extract('HOUR', expectedArrival, "yyyy-MM-dd'T'HH:mm:ss'Z'") as arrivalHour,
            time:extract('MINUTE', expectedArrival, "yyyy-MM-dd'T'HH:mm:ss'Z'") as arrivalMin,
            time:extract('HOUR', timeToLive, "yyyy-MM-dd'T'HH:mm:ss'Z'") as timeToLiveHour,
            time:extract('MINUTE', timeToLive, "yyyy-MM-dd'T'HH:mm:ss'Z'") as timeToLiveMin,
            timeToStation
    insert into ArrivalsInfoStream;

    from ArrivalsInfoStream as A join BusTimeTable as B
    on A.routeNo == B.routeNo and  A.stopId == B.stopId
    select A.routeNo, A.stopId, A.stopName, B.hour, B.minute, A.arrivalHour, A.arrivalMin,
        (B.hour * 60 + B.minute) - (A.arrivalHour * 60 + A.arrivalMin) as timeDiff, str:concat(A.routeNo, "-",A.stopId) as routeNoStopId
    insert into ArrivalTimeTableStream;

    partition with  (routeNoStopId of ArrivalTimeTableStream)
    begin
        from ArrivalTimeTableStream
        select routeNo, stopId, stopName, hour, minute, arrivalHour, arrivalMin,
                math:abs(timeDiff) as timeDiff,
                ifThenElse(timeDiff>=0, 'Ontime', "Delayed") as status
        order by timeDiff
        limit 1
        insert into ArrivalAnalysisStream;
    end;
    ```
1. Send multiple requests to the `BusStopsStream` using event simulator. (More than 5 times)

**Comment by niveathika** [comment]
@BuddhiWathsala As discussed offline, I am unable to reproduce this on my machine. Have you checked ed the ulimit in yours?
