### ISSUE TITLE
[Editor] issue in docker export Could not acquire image ID or digest following build

### ISSUE THREAD

**Issue by suhothayan** [siddhi-io/distribution#584]
**Description:**
got this error when try to push, no other error in the console 

```
Exception in thread "Thread-5" java.lang.IllegalStateException: Could not acquire image ID or digest following build
	at com.spotify.docker.client.shaded.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.getImageId(DefaultDockerClient.java:305)
	at com.spotify.docker.client.DefaultDockerClient$BuildProgressHandler.access$1200(DefaultDockerClient.java:294)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1501)
	at com.spotify.docker.client.DefaultDockerClient.build(DefaultDockerClient.java:1465)
	at io.siddhi.distribution.editor.core.internal.DockerBuilder.buildDockerImage(DockerBuilder.java:128)
	at io.siddhi.distribution.editor.core.internal.DockerBuilder.run(DockerBuilder.java:78)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by suhothayan** [comment]
This is occurring when "${LOGGER_HOST}" is added at the docker export phase

**Comment by pcnfernando** [comment]
@BuddhiWathsala is looking into this
