### ISSUE TITLE
Error in tooling which is deployed to Docker

### ISSUE THREAD

**Issue by xtrmstep** [siddhi-io/distribution#970]
Hi,

I'm getting the following error pretty often in the tooling. Almost always. To reproduce it you can start Siddhi application with Kafka sources and sinks, then stop, and then try to start again. After this steps I often see this error. To solve it I have to make docker-compose down and then up again.

[2020-06-16_06-41-04_706] ERROR {io.siddhi.extension.io.kafka.source.ConsumerKafkaGroup} - Error while creating KafkaConsumerThread for topic(s): [test_alert14_captured] 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@28aa6d94 rejected from java.util.concurrent.ThreadPoolExecutor@41a86e44[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.execute(Unknown Source)
	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
	at io.siddhi.extension.io.kafka.source.ConsumerKafkaGroup.run(ConsumerKafkaGroup.java:111)
	at io.siddhi.extension.io.kafka.source.KafkaSource.connect(KafkaSource.java:278)
	at io.siddhi.extension.io.kafka.source.KafkaSource.connect(KafkaSource.java:56)
	at io.siddhi.core.stream.input.source.Source.connectWithRetry(Source.java:160)
	at io.siddhi.core.SiddhiAppRuntimeImpl.startSources(SiddhiAppRuntimeImpl.java:502)
	at io.siddhi.core.SiddhiAppRuntimeImpl.start(SiddhiAppRuntimeImpl.java:427)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.start(DebugRuntime.java:93)
	at io.siddhi.distribution.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:42)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.start(EditorMicroservice.java:761)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.startWithVariables(EditorMicroservice.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by xtrmstep** [comment]
and with DB


[2020-06-16_07-20-10_885] ERROR {io.siddhi.core.table.Table} - Error on 'alert14_2_database'. Error initializing connection for store: alert14_captured Error while connecting to Table 'alert14_captured', will retry in '5 sec'. (Encoded) 
io.siddhi.core.exception.ConnectionUnavailableException: Error initializing connection for store: alert14_captured
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.getConnection(RDBMSEventTable.java:1391)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.getConnection(RDBMSEventTable.java:1376)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.tableExists(RDBMSEventTable.java:1654)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.connect(RDBMSEventTable.java:1229)
	at io.siddhi.core.table.record.AbstractQueryableRecordTable.connectAndLoadCache(AbstractQueryableRecordTable.java:206)
	at io.siddhi.core.table.Table.connectWithRetry(Table.java:406)
	at io.siddhi.core.SiddhiAppRuntimeImpl.startWithoutSources(SiddhiAppRuntimeImpl.java:455)
	at io.siddhi.core.SiddhiAppRuntimeImpl.start(SiddhiAppRuntimeImpl.java:424)
	at io.siddhi.distribution.editor.core.internal.DebugRuntime.start(DebugRuntime.java:93)
	at io.siddhi.distribution.editor.core.internal.DebugProcessorService.start(DebugProcessorService.java:42)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.start(EditorMicroservice.java:761)
	at io.siddhi.distribution.editor.core.internal.EditorMicroservice.startWithVariables(EditorMicroservice.java:781)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:187)
	at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.dispatchMethod(MSF4JHttpConnectorListener.java:218)
	at org.wso2.msf4j.internal.MSF4JHttpConnectorListener.lambda$onMessage$58(MSF4JHttpConnectorListener.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-2) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:96)
	at io.siddhi.extension.store.rdbms.RDBMSEventTable.getConnection(RDBMSEventTable.java:1388)
	... 22 more

**Comment by xtrmstep** [comment]
seems like relates to incorrect application name =/
